# Generated by Django 4.0.4 on 2022-04-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_item', models.CharField(max_length=250)),
                ('descricao_item', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sobreviventes',
            fields=[
                ('sobreviventes_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_sobrevivente', models.CharField(max_length=250)),
                ('idade_sobrevivente', models.IntegerField()),
                ('sexo_sobrevivente', models.CharField(max_length=50)),
                ('latitude_sobrevivente', models.FloatField()),
                ('longitude_sobrevivente', models.FloatField()),
                ('flags_infectado', models.IntegerField(null=True)),
                ('infectato', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sobreviventesinventario',
            fields=[
                ('Sobreviventesinventario_id', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='sobreviventes.inventario')),
                ('sobrevivente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobrevivente', to='sobreviventes.sobreviventes')),
            ],
        ),
        migrations.AddField(
            model_name='sobreviventes',
            name='Inventario',
            field=models.ManyToManyField(related_name='itens', through='sobreviventes.Sobreviventesinventario', to='sobreviventes.inventario'),
        ),
    ]
