# Generated by Django 4.0.4 on 2022-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0002_verifcaitens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifcaitens',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
