# Generated by Django 4.0.4 on 2022-04-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0003_alter_verifcaitens_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verifcaitens',
        ),
    ]
